apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hello-prod

resources:
  - ../../base

images:
  - name: hello-spring
    newTag: "0.0.2"

patches:
  - target:
      kind: ConfigMap
      name: hello-spring-config
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: hello-spring-config
      data:
        environment: prod
        message: "Hello from Prod!"

  - target:
      kind: Deployment
      name: hello-spring
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hello-spring
      spec:
        replicas: 2
        template:
          metadata:
            annotations:
              kubectl.kubernetes.io/restartedAt: "2026-05-25T18:35:00Z"
  - target:
      kind: Ingress
      name: hello-spring
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: hello-spring
      spec:
        rules:
          - host: hello-spring-prod.test
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: hello-spring
                      port:
                        number: 80
