apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hello-dev

resources:
  - ../../base

# Override the image tag — update this when you build a new image
images:
  - name: ghcr.io/abhijnanacharya/hello-spring
    newTag: "fd8a4929b72c638796c617e458ffb9283b70021d"

patches:
  # Patch the ConfigMap values for dev
  - target:
      kind: ConfigMap
      name: hello-spring-config
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: hello-spring-config
      data:
        environment: dev
        message: "Hello from GitOps!!!"

  # Patch replica count + restart annotation for dev
  - target:
      kind: Deployment
      name: hello-spring
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hello-spring
      spec:
        replicas: 2
        template:
          metadata:
            annotations:
              kubectl.kubernetes.io/restartedAt: "2026-05-28T08:43:03Z"
